"""Shared terminal theme for the Riff Band CLI."""

APP_NAME = "Riff Band"
CLI_NAME = "Riff Band CLI"

COLOR_SOFT = "#dcd3ea"
COLOR_MID = "#bba9cb"
COLOR_DEEP = "#a190af"

COLOR_SUCCESS = "#8fb59a"
COLOR_ERROR = "#c28f8f"
COLOR_WARNING = "#c9b77d"
COLOR_INFO = "#8fa8bd"

BRAND = f"bold {COLOR_SOFT}"
ACCENT = f"bold {COLOR_DEEP}"
MUTED = COLOR_MID
BORDER = COLOR_DEEP
PANEL = COLOR_MID

SUCCESS = COLOR_SUCCESS
SUCCESS_BOLD = f"bold {COLOR_SUCCESS}"
ERROR = COLOR_ERROR
ERROR_BOLD = f"bold {COLOR_ERROR}"
WARNING = COLOR_WARNING
WARNING_BOLD = f"bold {COLOR_WARNING}"
INFO = COLOR_INFO
INFO_BOLD = f"bold {COLOR_INFO}"
